# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 07:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book_review', '0002_auto_20161118_0644'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=225)),
                ('rating', models.DecimalField(decimal_places=0, max_digits=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='comments',
            name='book',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='commenter',
        ),
        migrations.RemoveField(
            model_name='books',
            name='rating',
        ),
        migrations.AlterField(
            model_name='books',
            name='review',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='bookreview', to='book_review.Reviews'),
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
        migrations.AddField(
            model_name='reviews',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='commentbook', to='book_review.Books'),
        ),
        migrations.AddField(
            model_name='reviews',
            name='commenter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='commentuser', to='book_review.Users'),
        ),
    ]
